Repository AY2122S2-CS2103T-W13-4/tp, pull requests merged in 2022-04, with the labels that each got.

#228 Fix issue of policy commands not throwing errors correctly
  src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/policy/UniquePolicyList.java
  src/main/java/seedu/address/model/policy/exceptions/EmptyPolicyListException.java
  src/main/java/seedu/address/model/policy/exceptions/PolicyNotEditedException.java
Labels: priority.High, type.Bug

#227 Change PREFIX for preference key and details
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.High, type.Bug

#231 Fix the 'bug' that meetings command does not work
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/meeting/AddMeetingCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, severity.Medium

#232 Fix the bug that invalid dates could be added
  src/main/java/seedu/address/logic/commands/meeting/AddMeetingCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/meeting/AddMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/Meeting.java
Labels: type.Bug, severity.Medium

#234 Update ug for sort
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
Labels: priority.High, type.Bug

#237 [PE-D] Fix user guide
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#235 Fix last contacted hidden when name is too long
  src/main/resources/view/ClientListCard.fxml
Labels: type.Bug, severity.Medium

#236 Fix exit not closing tutorial window
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, severity.Low

#238 Fix right panel not resizing
  src/main/resources/view/ClientDisplayPanel.fxml
Labels: type.Bug, severity.Low

#239 Fix client view remaining after delete
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, severity.Medium

#240 187: Fix bug where empty note can be used for addNote
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
Labels: priority.Medium, type.Bug

#244 Empty client list bugs
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High, type.Bug

#247 fix clear bug when client is displayed
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: priority.High, type.Bug

#243 [PE-D] Fix `lastContacted`
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ContactedCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/DateTime.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
Labels: type.Bug, severity.Medium

#245 [PE-D] Fix `addClient` and `editClient` commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/client/Email.java
Labels: type.Bug, severity.Medium

#249 Add test cases to check that command exception is thrown when ab is empty
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: priority.High, type.Task

#253 Add test suites for all classes related to Policy model
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
  src/main/java/seedu/address/model/policy/UniquePolicyList.java
  src/main/java/seedu/address/model/policy/exceptions/PolicyNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPolicy.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/policy/AddPolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/policy/DeletePolicyCommandTest.java
  src/test/java/seedu/address/logic/commands/policy/EditPolicyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/policy/AddPolicyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/policy/DeletePolicyParserTest.java
  src/test/java/seedu/address/logic/parser/policy/EditPolicyParserTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/policy/PolicyTest.java
  src/test/java/seedu/address/model/policy/PremiumTest.java
  src/test/java/seedu/address/model/policy/UniquePolicyListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPolicyTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/PolicyBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/seedu/address/testutil/TypicalPolicies.java
Labels: priority.High, type.Task

#255 Updated ppp for Zech
  docs/images/sample-output/PPPPreferenceFeatureDeleted.png
  docs/images/sample-output/PPPPreferenceFeatureOutput.png
  docs/images/zech-ppp/PPPNotesFeatureDeleted.png
  docs/images/zech-ppp/PPPNotesFeatureInitial.png
  docs/images/zech-ppp/PPPNotesFeatureOutput.png
  docs/images/zech-ppp/PPPPreferenceFeatureInitial.png
  docs/team/zechajw.md
Labels: priority.High, type.Enhancement

#252 Write tests for meeting-related code
  src/main/java/seedu/address/logic/commands/meeting/DeleteMeetingCommand.java
  src/main/java/seedu/address/model/meeting/NonOverlappingMeetingList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/meeting/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/meeting/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/meeting/ListMeetingCommandTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/model/meeting/NonOverlappingMeetingTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: priority.Medium, type.Enhancement

#256 Update draft PPP
  docs/team/raynerljm.md
Labels: priority.Medium, type.Task

#259 Update PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/myc37.md
  docs/team/sheimoria.md
Labels: priority.Medium, type.Task

#262 Fix invalid `birthday`s
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Date.java
  src/main/java/seedu/address/model/client/DateTime.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
Labels: type.Bug, severity.Medium

#266 Update UG and DG for meetings
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Meeting1Add.png
  docs/images/Meeting1Add1.png
  docs/images/Meeting1Add2.png
  docs/images/Meeting2List.png
  docs/images/Meeting2List1.png
  docs/images/Meeting3Edit1.png
  docs/images/Meeting3Edit2.png
  docs/images/Meeting3Update.png
  docs/images/Meeting4Delete.png
  docs/images/Meeting4Delete1.png
  docs/images/Meeting4Delete2.png
  docs/images/Meeting5Close1.png
  docs/images/Meeting5Close2.png
Labels: priority.Low, type.Task

#263 Add tests for `birthday` and `lastContacted`
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ContactedCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ContactedCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/DateTest.java
  src/test/java/seedu/address/model/client/DateTimeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: priority.Medium, type.Task

#268 Issue 92: Add preference tests
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/model/client/PreferenceMap.java
  src/test/java/seedu/address/logic/commands/AddPreferenceCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePreferenceCommandTest.java
  src/test/java/seedu/address/model/client/PreferenceMapTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PreferenceMapBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPreferenceMap.java
Labels: priority.High, type.Enhancement

#272 Parse tests
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/meeting/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meeting/ListMeetingCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/meeting/AddMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meeting/DeleteMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meeting/EditMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meeting/ListMeetingCommandParserTest.java
Labels: type.Enhancement

#270 Add note tests
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddPreferenceCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ContactedCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePreferenceCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewClientCommandParserTest.java
  src/test/java/seedu/address/model/client/NoteTest.java
  src/test/java/seedu/address/model/client/SortCriteriaTest.java
  src/test/java/seedu/address/testutil/NoteBuilder.java
  src/test/java/seedu/address/testutil/TypicalNote.java
Labels: priority.High, type.Enhancement

#279 Refactor `Date` to `Birthday` and `DateTime` to `LastContacted`
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ContactedCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Birthday.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/LastContacted.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ContactedCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/client/BirthdayTest.java
  src/test/java/seedu/address/model/client/DateTest.java
  src/test/java/seedu/address/model/client/DateTimeTest.java
  src/test/java/seedu/address/model/client/LastContactedTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
Labels: priority.Low, type.Enhancement

#283 Add tests for `contacted` command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/ContactedCommandParser.java
  src/test/java/seedu/address/logic/parser/ContactedCommandParserTest.java
Labels: priority.Low, type.Enhancement

#280 rayner ppp final
  docs/team/raynerljm.md
Labels: type.Enhancement
