Repository AY2122S2-CS2103T-W13-4/tp, pull requests merged in 2022-03, with the labels that each got.

#41 Update `README`
  README.md
  docs/images/Ui.png
  docs/images/Ui_old.png
Labels: documentation

#45 Add skeletal ppp for sheimoria
  docs/team/sheimoria.md
Labels: documentation

#46 Add table of contents to user guide
  docs/UserGuide.md
Labels: documentation

#47 Link CI banner to project
  README.md
Labels: documentation

#49 Update site-wide settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: documentation

#54 Issue #12: As a first time user I can schedule meetings with clients
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/NonOverlappingMeetingList.java
  src/main/java/seedu/address/model/meeting/exceptions/MeetingNotFoundException.java
  src/main/java/seedu/address/model/meeting/exceptions/OverlappingMeetingsException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High, type.Story, type.Enhancement

#55 15 add client policies
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/policy/AddPolicyCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/policy/Policy.java
  src/main/java/seedu/address/model/policy/Premium.java
  src/main/java/seedu/address/model/policy/exceptions/DuplicatePolicyException.java
Labels: priority.High, type.Story

#57 issue #52: create tutorial
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/TutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TutorialWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TutorialWindow.css
  src/main/resources/view/TutorialWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, type.Story

#61 13 last contacted
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/DateTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/resources/view/DarkTheme.css
Labels: priority.High, type.Story

#62 Issue #11 and #16
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/MeetingListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingListCard.fxml
  src/main/resources/view/MeetingListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Story

#68 Issue #60: Add side panel to display more information
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingListPanel.fxml
Labels: priority.Medium, type.Enhancement

#70 Issue#59 save policy
  src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
  src/main/java/seedu/address/model/policy/Policy.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPolicy.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.High

#74 Issue #58: Fix save functionality for Notes and add to GUI
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.High

#77 Issue #67: Fix save functionality for preferences
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PreferenceMap.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedPreferenceMap.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, severity.High

#79 Add functionality for ViewPolicy command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/policy/ViewPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/policy/ViewPolicyCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/policy/Policy.java
Labels: priority.High, type.Story

#73 Update UG
  docs/UserGuide.md
  docs/images/gui-sample.jpg
Labels: priority.Medium, type.Task

#81 Add birthday
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Date.java
  src/main/java/seedu/address/model/person/DateTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: priority.High, type.Story

#103 Add DeletePolicy command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/ViewPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/policy/DeletePolicyCommandParser.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/policy/Policy.java
  src/main/java/seedu/address/model/policy/exceptions/InvalidPolicyIndexException.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High, type.Story

#104 Issue#91 update policy
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/policy/AddPolicyCommandParser.java
  src/main/java/seedu/address/logic/parser/policy/DeletePolicyCommandParser.java
  src/main/java/seedu/address/logic/parser/policy/EditPolicyCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedPolicy.java
Labels: priority.High, type.Story

#108 87/edit person meeting
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/NonOverlappingMeetingList.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: priority.High, type.Bug

#109 Update DG and write about Meetings implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Meeting1Add.png
  docs/images/Meeting2List.png
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
Labels: type.Enhancement

#112 111/meeting label
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidMeetingAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/overlappingMeetingsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalMeetingsAddressBook.json
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: type.Enhancement

#117 Issue 94: Add DeletePreferenceCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePreferenceCommandParser.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/PreferenceMap.java
  src/main/java/seedu/address/model/client/exceptions/InvalidPreferenceKeyException.java
Labels: priority.High, type.Story

#114 99/remove view policy
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/policy/ViewPolicyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/policy/ViewPolicyCommandParser.java
Labels: priority.Low, type.Task

#120 Add `ContactedCommand`
  src/main/java/seedu/address/logic/commands/ContactedCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ContactedCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/client/DateTime.java
Labels: priority.High, type.Enhancement

#123 Fix minor bug and update DG
  docs/DeveloperGuide.md
  docs/images/Meeting3Update.png
  docs/images/Meeting4Delete.png
  src/main/java/seedu/address/logic/commands/meeting/EditMeetingCommand.java
Labels: type.Bug, severity.High

#125 Create view client view
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/TutorialCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/main/java/seedu/address/logic/commands/meeting/ListMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewClientCommandParser.java
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/java/seedu/address/ui/ClientDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/PolicyCard.java
  src/main/java/seedu/address/ui/PolicyListPanel.java
  src/main/resources/images/profile.png
  src/main/resources/view/ClientDisplayPanel.fxml
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Lato-Black.ttf
  src/main/resources/view/Lato-Bold.ttf
  src/main/resources/view/Lato-Light.ttf
  src/main/resources/view/Lato-Regular.ttf
  src/main/resources/view/Lato-Thin.ttf
  src/main/resources/view/PolicyListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, type.Enhancement

#127 Update documentation with `lastContacted` and `ContactedCommand` feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/LastContacted1.png
  docs/images/LastContacted2.png
  docs/images/LastContacted3.png
Labels: priority.Medium, type.Task

#132 Update Meeting implementation and update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/meeting/EditMeetingCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/ui/MeetingCard.java
Labels: priority.Medium, type.Enhancement

#136 135 meetings filter
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/meeting/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meeting/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meeting/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meeting/ListMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/meeting/ListMeetingCommandParser.java
Labels: priority.Medium, type.Enhancement

#143 Fix loading `birthday` or `lastContacted`
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/client/Date.java
  src/main/java/seedu/address/model/client/DateTime.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
Labels: priority.High, type.Bug

#141 Add option to view upcoming meetings or all meetings and change sort direction
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/meeting/ListMeetingCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/meeting/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/meeting/ListMeetingCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/NonOverlappingMeetingList.java
Labels: priority.Medium, type.Enhancement

#145 Make `email` and `address` parameters optional for `addClient` command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/client/Address.java
  src/main/java/seedu/address/model/client/Email.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/ClientBuilder.java
Labels: priority.Medium, type.Enhancement

#146 Add sort by premium
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/policy/Premium.java
  src/main/java/seedu/address/model/policy/UniquePolicyList.java
Labels: priority.High, type.Story

#149 Add `birthday` and `lastContacted` as optional parameters to the `addClient` command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClient.java
  src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/overlappingMeetingsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalMeetingsAddressBook.json
Labels: priority.Medium, type.Enhancement

#150 Add `lastContacted` preamble support in `sortClients` command to sort clients by `lastContacted`
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/client/DateTime.java
Labels: priority.Medium, type.Story

#153 Add filter command for age
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Date.java
Labels: priority.High, type.Story

#155 Add `clientCount` and `sortCriteria` to `ClientListPanel` and fix `ClientDisplay` not updating on edit client
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/TutorialCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/main/java/seedu/address/logic/commands/meeting/ListMeetingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/SortCriteria.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ClientListCard.fxml
  src/main/resources/view/ClientListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PolicyListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, type.Enhancement, type.Bug, severity.Medium

#157 Fix client card not updating on add policy
  src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
Labels: priority.High, type.Bug

#163 Fix incorrect client index after sort
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/main/java/seedu/address/logic/commands/meeting/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meeting/ListMeetingCommand.java
  src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Bug

#160 Add filter functionality for birthMonth
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/Date.java
Labels: priority.High, type.Story

#165 Fix client view not updating on edit after sort
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewClientCommand.java
  src/main/java/seedu/address/logic/commands/policy/AddPolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/DeletePolicyCommand.java
  src/main/java/seedu/address/logic/commands/policy/EditPolicyCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Bug
